from enum import StrEnum


class RecordStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class AdmissionCycleStatus(StrEnum):
    DRAFT = "DRAFT"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class DataSourceType(StrEnum):
    API = "API"
    WEB_PAGE = "WEB_PAGE"
    DOCUMENT = "DOCUMENT"
    DATASET = "DATASET"


class ReleaseStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class IngestionRunStatus(StrEnum):
    RECEIVED = "RECEIVED"
    PARSED = "PARSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class StagedRecordStatus(StrEnum):
    RAW = "RAW"
    PARSED = "PARSED"
    NORMALIZED = "NORMALIZED"
    VALIDATED = "VALIDATED"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"


class FindingSeverity(StrEnum):
    WARNING = "WARNING"
    ERROR = "ERROR"


class ResourceLinkType(StrEnum):
    OFFICIAL_WEBSITE = "OFFICIAL_WEBSITE"
    ADMISSIONS_PAGE = "ADMISSIONS_PAGE"
    COUNSELLING_PAGE = "COUNSELLING_PAGE"
    PROGRAM_PAGE = "PROGRAM_PAGE"
    SCHOLARSHIP_PAGE = "SCHOLARSHIP_PAGE"
    APPLICATION_PAGE = "APPLICATION_PAGE"
    GUIDELINES_PAGE = "GUIDELINES_PAGE"
    SOURCE_DOCUMENT = "SOURCE_DOCUMENT"


class ResourceEntityType(StrEnum):
    INSTITUTION = "INSTITUTION"
    PROGRAM = "PROGRAM"
    SCHOLARSHIP = "SCHOLARSHIP"
    COUNSELLING_AUTHORITY = "COUNSELLING_AUTHORITY"
    SOURCE_AUTHORITY = "SOURCE_AUTHORITY"


class ScholarshipProviderType(StrEnum):
    CENTRAL_GOVERNMENT = "CENTRAL_GOVERNMENT"
    STATE_GOVERNMENT = "STATE_GOVERNMENT"
    INSTITUTION = "INSTITUTION"
    PRIVATE_VERIFIED = "PRIVATE_VERIFIED"


class ScholarshipStatus(StrEnum):
    DRAFT = "DRAFT"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class EligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    NEEDS_INFORMATION = "NEEDS_INFORMATION"


class EligibilitySubjectType(StrEnum):
    PROGRAM = "PROGRAM"
    SCHOLARSHIP = "SCHOLARSHIP"


class RuleEvaluationStatus(StrEnum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    MISSING = "MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    CONFLICT = "CONFLICT"
