"""phase 4 deterministic eligibility engine

Revision ID: 21d50b232e4f
Revises: 626861980204
Create Date: 2026-09-09 21:47:44.024426
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "21d50b232e4f"
down_revision: str | None = "626861980204"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

eligibility_subject_type = postgresql.ENUM(
    "PROGRAM", "SCHOLARSHIP", name="eligibility_subject_type", create_type=False
)
eligibility_status = postgresql.ENUM(
    "ELIGIBLE",
    "INELIGIBLE",
    "NEEDS_INFORMATION",
    name="eligibility_status",
    create_type=False,
)
rule_evaluation_status = postgresql.ENUM(
    "PASSED",
    "FAILED",
    "MISSING",
    "NOT_APPLICABLE",
    "CONFLICT",
    name="rule_evaluation_status",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    eligibility_subject_type.create(bind, checkfirst=True)
    eligibility_status.create(bind, checkfirst=True)
    rule_evaluation_status.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eligibility_input_snapshots",
        sa.Column("profile_identifier", sa.String(length=255), nullable=True),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("evaluation_year", sa.SmallInteger(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_input", sa.JSON(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "evaluation_year >= 2000 AND evaluation_year <= 2100",
            name=op.f("ck_eligibility_input_snapshots_year_range"),
        ),
        sa.CheckConstraint(
            "length(input_hash) = 64", name=op.f("ck_eligibility_input_snapshots_sha256_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_input_snapshots")),
    )
    op.create_index(
        "ix_eligibility_snapshots_hash", "eligibility_input_snapshots", ["input_hash"], unique=False
    )
    op.create_table(
        "eligibility_evaluations",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", eligibility_subject_type, nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_year", sa.SmallInteger(), nullable=False),
        sa.Column("status", eligibility_status, nullable=False),
        sa.Column("rule_set_version", sa.String(length=128), nullable=False),
        sa.Column("catalog_release_id", sa.Uuid(), nullable=True),
        sa.Column("rules_hash", sa.String(length=64), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("missing_information", sa.JSON(), nullable=False),
        sa.Column("human_summary", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "evaluation_year >= 2000 AND evaluation_year <= 2100",
            name=op.f("ck_eligibility_evaluations_year_range"),
        ),
        sa.CheckConstraint(
            "length(rules_hash) = 64", name=op.f("ck_eligibility_evaluations_rules_sha256_length")
        ),
        sa.ForeignKeyConstraint(
            ["catalog_release_id"],
            ["catalog_releases.id"],
            name=op.f("fk_eligibility_evaluations_catalog_release_id_catalog_releases"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["eligibility_input_snapshots.id"],
            name=op.f("fk_eligibility_evaluations_snapshot_id_eligibility_input_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_evaluations")),
    )
    op.create_index(
        op.f("ix_eligibility_evaluations_snapshot_id"),
        "eligibility_evaluations",
        ["snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_eligibility_evaluations_subject_year",
        "eligibility_evaluations",
        ["subject_type", "subject_id", "evaluation_year"],
        unique=False,
    )
    op.create_table(
        "eligibility_rule_results",
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("parent_result_id", sa.Uuid(), nullable=True),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("rule_version", sa.String(length=128), nullable=False),
        sa.Column("status", rule_evaluation_status, nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("observed_value", sa.JSON(), nullable=True),
        sa.Column("expected_value", sa.JSON(), nullable=True),
        sa.Column("source_document_version_id", sa.Uuid(), nullable=True),
        sa.Column("source_locator", sa.String(length=500), nullable=True),
        sa.Column("official_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["eligibility_evaluations.id"],
            name=op.f("fk_eligibility_rule_results_evaluation_id_eligibility_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_result_id"],
            ["eligibility_rule_results.id"],
            name=op.f("fk_eligibility_rule_results_parent_result_id_eligibility_rule_results"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_version_id"],
            ["source_document_versions.id"],
            name=op.f(
                "fk_eligibility_rule_results_source_document_version_id_source_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_rule_results")),
        sa.UniqueConstraint(
            "evaluation_id", "sequence", name=op.f("uq_eligibility_rule_results_evaluation_id")
        ),
    )
    op.create_index(
        op.f("ix_eligibility_rule_results_evaluation_id"),
        "eligibility_rule_results",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eligibility_rule_results_parent_result_id"),
        "eligibility_rule_results",
        ["parent_result_id"],
        unique=False,
    )
    op.create_index(
        "ix_eligibility_rule_results_rule",
        "eligibility_rule_results",
        ["rule_id", "rule_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eligibility_rule_results_source_document_version_id"),
        "eligibility_rule_results",
        ["source_document_version_id"],
        unique=False,
    )
    op.create_table(
        "eligibility_evaluation_resource_links",
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("resource_link_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["eligibility_evaluations.id"],
            name=op.f(
                "fk_eligibility_evaluation_resource_links_evaluation_id_eligibility_evaluations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_link_id"],
            ["resource_links.id"],
            name=op.f("fk_eligibility_evaluation_resource_links_resource_link_id_resource_links"),
        ),
        sa.PrimaryKeyConstraint(
            "evaluation_id",
            "resource_link_id",
            name=op.f("pk_eligibility_evaluation_resource_links"),
        ),
    )
    op.add_column(
        "admission_requirement_subjects",
        sa.Column("minimum_marks", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.create_check_constraint(
        op.f("ck_admission_requirement_subjects_marks_range"),
        "admission_requirement_subjects",
        "minimum_marks IS NULL OR (minimum_marks >= 0 AND minimum_marks <= 100)",
    )
    op.add_column(
        "admission_requirements", sa.Column("domicile_state_id", sa.Uuid(), nullable=True)
    )
    op.add_column("admission_requirements", sa.Column("gender_pool_id", sa.Uuid(), nullable=True))
    op.add_column("admission_requirements", sa.Column("quota_type_id", sa.Uuid(), nullable=True))
    op.add_column(
        "admission_requirements",
        sa.Column("minimum_exam_score", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "admission_requirements", sa.Column("maximum_exam_rank", sa.Integer(), nullable=True)
    )
    op.add_column(
        "admission_requirements", sa.Column("minimum_age", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "admission_requirements", sa.Column("maximum_age", sa.SmallInteger(), nullable=True)
    )
    op.add_column("admission_requirements", sa.Column("required_pwd", sa.Boolean(), nullable=True))
    op.add_column("admission_requirements", sa.Column("required_ews", sa.Boolean(), nullable=True))
    op.add_column(
        "admission_requirements", sa.Column("nationality_code", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "admission_requirements", sa.Column("source_locator", sa.String(length=500), nullable=True)
    )
    op.drop_constraint("uq_admission_requirement_scope", "admission_requirements", type_="unique")
    op.create_unique_constraint(
        "uq_admission_requirement_scope",
        "admission_requirements",
        [
            "code",
            "academic_year",
            "category_id",
            "institution_id",
            "program_id",
            "rule_version",
        ],
    )
    for name, condition in (
        ("exam_score_non_negative", "minimum_exam_score IS NULL OR minimum_exam_score >= 0"),
        ("exam_rank_positive", "maximum_exam_rank IS NULL OR maximum_exam_rank > 0"),
        ("minimum_age_non_negative", "minimum_age IS NULL OR minimum_age >= 0"),
        ("maximum_age_non_negative", "maximum_age IS NULL OR maximum_age >= 0"),
        (
            "age_order",
            "minimum_age IS NULL OR maximum_age IS NULL OR minimum_age <= maximum_age",
        ),
    ):
        op.create_check_constraint(
            op.f(f"ck_admission_requirements_{name}"), "admission_requirements", condition
        )
    op.create_index(
        op.f("ix_admission_requirements_domicile_state_id"),
        "admission_requirements",
        ["domicile_state_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_requirements_gender_pool_id"),
        "admission_requirements",
        ["gender_pool_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_requirements_quota_type_id"),
        "admission_requirements",
        ["quota_type_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_admission_requirements_domicile_state_id_states"),
        "admission_requirements",
        "states",
        ["domicile_state_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_admission_requirements_quota_type_id_quota_types"),
        "admission_requirements",
        "quota_types",
        ["quota_type_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_admission_requirements_gender_pool_id_gender_pools"),
        "admission_requirements",
        "gender_pools",
        ["gender_pool_id"],
        ["id"],
    )
    op.add_column(
        "scholarship_eligibility_rules",
        sa.Column("source_locator", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scholarship_eligibility_rules", "source_locator")
    for name in (
        "age_order",
        "maximum_age_non_negative",
        "minimum_age_non_negative",
        "exam_rank_positive",
        "exam_score_non_negative",
    ):
        op.drop_constraint(
            op.f(f"ck_admission_requirements_{name}"),
            "admission_requirements",
            type_="check",
        )
    op.drop_constraint("uq_admission_requirement_scope", "admission_requirements", type_="unique")
    op.create_unique_constraint(
        "uq_admission_requirement_scope",
        "admission_requirements",
        ["code", "academic_year", "category_id", "program_id"],
    )
    op.drop_constraint(
        op.f("fk_admission_requirements_gender_pool_id_gender_pools"),
        "admission_requirements",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_admission_requirements_quota_type_id_quota_types"),
        "admission_requirements",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_admission_requirements_domicile_state_id_states"),
        "admission_requirements",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_admission_requirements_quota_type_id"), table_name="admission_requirements"
    )
    op.drop_index(
        op.f("ix_admission_requirements_gender_pool_id"), table_name="admission_requirements"
    )
    op.drop_index(
        op.f("ix_admission_requirements_domicile_state_id"), table_name="admission_requirements"
    )
    op.drop_column("admission_requirements", "source_locator")
    op.drop_column("admission_requirements", "nationality_code")
    op.drop_column("admission_requirements", "required_ews")
    op.drop_column("admission_requirements", "required_pwd")
    op.drop_column("admission_requirements", "maximum_age")
    op.drop_column("admission_requirements", "minimum_age")
    op.drop_column("admission_requirements", "maximum_exam_rank")
    op.drop_column("admission_requirements", "minimum_exam_score")
    op.drop_column("admission_requirements", "quota_type_id")
    op.drop_column("admission_requirements", "gender_pool_id")
    op.drop_column("admission_requirements", "domicile_state_id")
    op.drop_constraint(
        op.f("ck_admission_requirement_subjects_marks_range"),
        "admission_requirement_subjects",
        type_="check",
    )
    op.drop_column("admission_requirement_subjects", "minimum_marks")
    op.drop_table("eligibility_evaluation_resource_links")
    op.drop_index(
        op.f("ix_eligibility_rule_results_source_document_version_id"),
        table_name="eligibility_rule_results",
    )
    op.drop_index("ix_eligibility_rule_results_rule", table_name="eligibility_rule_results")
    op.drop_index(
        op.f("ix_eligibility_rule_results_parent_result_id"), table_name="eligibility_rule_results"
    )
    op.drop_index(
        op.f("ix_eligibility_rule_results_evaluation_id"), table_name="eligibility_rule_results"
    )
    op.drop_table("eligibility_rule_results")
    op.drop_index("ix_eligibility_evaluations_subject_year", table_name="eligibility_evaluations")
    op.drop_index(
        op.f("ix_eligibility_evaluations_snapshot_id"), table_name="eligibility_evaluations"
    )
    op.drop_table("eligibility_evaluations")
    op.drop_index("ix_eligibility_snapshots_hash", table_name="eligibility_input_snapshots")
    op.drop_table("eligibility_input_snapshots")
    bind = op.get_bind()
    rule_evaluation_status.drop(bind, checkfirst=True)
    eligibility_status.drop(bind, checkfirst=True)
    eligibility_subject_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
