"""phase 5 deterministic ranking engine

Revision ID: f910e48492d8
Revises: 21d50b232e4f
Create Date: 2026-09-09 23:13:51.285802
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f910e48492d8"
down_revision: str | None = "21d50b232e4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ranking_domain = postgresql.ENUM("COLLEGE", "SCHOLARSHIP", name="ranking_domain", create_type=False)


def upgrade() -> None:
    ranking_domain.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ranking_profiles",
        sa.Column("profile_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("domain", ranking_domain, nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.Column("normalization_version", sa.String(length=64), nullable=False),
        sa.Column("tie_breaking_version", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_profiles")),
        sa.UniqueConstraint(
            "profile_key", "version", "domain", name=op.f("uq_ranking_profiles_profile_key")
        ),
    )
    op.create_table(
        "ranking_runs",
        sa.Column("domain", ranking_domain, nullable=False),
        sa.Column("ranking_profile_id", sa.Uuid(), nullable=False),
        sa.Column("profile_hash", sa.String(length=64), nullable=False),
        sa.Column("preference_hash", sa.String(length=64), nullable=False),
        sa.Column("preference_snapshot", sa.JSON(), nullable=False),
        sa.Column("ranking_profile_snapshot", sa.JSON(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("needs_information_ids", sa.JSON(), nullable=False),
        sa.Column("excluded_ineligible_ids", sa.JSON(), nullable=False),
        sa.Column("excluded_inactive_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "length(preference_hash) = 64", name=op.f("ck_ranking_runs_preference_hash_length")
        ),
        sa.CheckConstraint(
            "length(profile_hash) = 64", name=op.f("ck_ranking_runs_profile_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["ranking_profile_id"],
            ["ranking_profiles.id"],
            name=op.f("fk_ranking_runs_ranking_profile_id_ranking_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_runs")),
    )
    op.create_index(
        "ix_ranking_runs_domain_evaluated", "ranking_runs", ["domain", "evaluated_at"], unique=False
    )
    op.create_index(
        op.f("ix_ranking_runs_ranking_profile_id"),
        "ranking_runs",
        ["ranking_profile_id"],
        unique=False,
    )
    op.create_table(
        "ranked_recommendations",
        sa.Column("ranking_run_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("eligibility_evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("rank_position", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("tier", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.String(length=64), nullable=False),
        sa.Column("component_scores", sa.JSON(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("deterministic_summary", sa.Text(), nullable=False),
        sa.Column("official_links", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 1",
            name=op.f("ck_ranked_recommendations_score_range"),
        ),
        sa.CheckConstraint(
            "rank_position > 0", name=op.f("ck_ranked_recommendations_positive_position")
        ),
        sa.ForeignKeyConstraint(
            ["eligibility_evaluation_id"],
            ["eligibility_evaluations.id"],
            name=op.f(
                "fk_ranked_recommendations_eligibility_evaluation_id_eligibility_evaluations"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["ranking_run_id"],
            ["ranking_runs.id"],
            name=op.f("fk_ranked_recommendations_ranking_run_id_ranking_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranked_recommendations")),
        sa.UniqueConstraint("ranking_run_id", "rank_position", name="uq_ranked_run_position"),
        sa.UniqueConstraint("ranking_run_id", "subject_id", name="uq_ranked_run_subject"),
    )
    op.create_index(
        op.f("ix_ranked_recommendations_eligibility_evaluation_id"),
        "ranked_recommendations",
        ["eligibility_evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ranked_recommendations_ranking_run_id"),
        "ranked_recommendations",
        ["ranking_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_ranked_recommendations_subject",
        "ranked_recommendations",
        ["subject_id", "ranking_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ranked_recommendations_subject", table_name="ranked_recommendations")
    op.drop_index(
        op.f("ix_ranked_recommendations_ranking_run_id"), table_name="ranked_recommendations"
    )
    op.drop_index(
        op.f("ix_ranked_recommendations_eligibility_evaluation_id"),
        table_name="ranked_recommendations",
    )
    op.drop_table("ranked_recommendations")
    op.drop_index(op.f("ix_ranking_runs_ranking_profile_id"), table_name="ranking_runs")
    op.drop_index("ix_ranking_runs_domain_evaluated", table_name="ranking_runs")
    op.drop_table("ranking_runs")
    op.drop_table("ranking_profiles")
    ranking_domain.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
