from __future__ import annotations

from decimal import Decimal
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class ExplanationContent(BaseModel):
    """The only fields Gemini is allowed to generate."""

    model_config = ConfigDict(extra="forbid")

    summary: str = Field(min_length=1, max_length=700)
    reasons: list[str] = Field(min_length=1, max_length=5)
    caveats: list[str] = Field(default_factory=list, max_length=4)
    next_steps: list[str] = Field(min_length=1, max_length=4)

    @field_validator("reasons", "caveats", "next_steps")
    @classmethod
    def validate_items(cls, value: list[str]) -> list[str]:
        if any(not item.strip() or len(item) > 300 for item in value):
            raise ValueError("Explanation list items must be concise and non-empty")
        return value


class AuthoritativeFacts(BaseModel):
    """Immutable facts copied from ScholarRoute, never generated by Gemini."""

    recommendation_id: UUID | None = None
    eligibility_evaluation_id: UUID
    subject_id: UUID
    fit_score: Decimal | None = None
    tier: str | None = None
    confidence: str | None = None
    eligibility_status: str
    ranking_profile_version: str | None = None


class ExplanationResponse(BaseModel):
    explanation_type: Literal["college", "scholarship", "eligibility"]
    model: str
    prompt_version: str
    explanation: ExplanationContent
    authoritative: AuthoritativeFacts
    official_links: list[str]
